### PR TITLE
Added Casino room object: Roulette

### PR DESCRIPTION
**Pull request by hwoarangmy**

### CODE REVIEW

**Comment by hwoarangmy** [comment]
@OpenDungeons/developers Shall I merge this one myself ?

**Comment by Bertram25** [comment]
Oops, sorry.

**Comment by hwoarangmy** [comment]
No problem. I was not really sure what the process was for the media repo as I don't know who has blender.

**Comment by akien-mga** [comment]
For the media repo I think we can automerge, but still do PRs so that the other contributors are notified of changes.

**Comment by hwoarangmy** [comment]
ok

**Comment by Danimal696** [comment]
did you bake an oclussion map? you can ovelay over the plain texture and get some pretty nice shading, thats what i do with all my models

**Comment by hwoarangmy** [comment]
You mean a normals ? If so, yes, I did.

**Comment by Danimal696** [comment]
No, an ambient oclusion map:
http://www.katsbits.com/tutorials/blender/basic-ambient-occlusion.php

One of the basic tricks to make things look good

**Comment by Bertram25** [comment]
Most artist do that directly on the texture, or am I wrong?

**Comment by hwoarangmy** [comment]
I have not done that. I will have a look, thanks

**Comment by Danimal696** [comment]
Its the easiest way to add realistic shades to a model, the generated AOmap can be used as a multiplier layer over the texture, turning a shadeless texture into something nice.

**Pull request merged**
